var Establ_educacionales_Petorca_ = {
    "type": "FeatureCollection",
    "name": "Establ_educacionales_Petorca repro",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        }
    },
    "features": [
        {
            "type": "Feature",
            "properties": {
                "fid": 808.0,
                "AGNO": 2020.0,
                "RBD": 1147.0,
                "DGV_RBD": 9.0,
                "NOM_RBD": "ESCUELA FERNANDO GARCIA OLDINI",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "COMERCIO HIERRO VIEJO",
                "NUMERO": 36.0,
                "REFERENCIA": "CALLE PRINCIPAL",
                "LATITUD": -32.28054,
                "LONGITUD": -71.011673,
                "MAT_TOT": 117.0,
                "MAT_PARV": 26.0,
                "MAT_BAS_RE": 91.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 65.0,
                "MAT_MUJ_TO": 52.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 117.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 107.0,
                "MAT_SI_ETN": 10.0,
                "CUR_SIM_TO": 10.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.011673,
                    -32.28054
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 809.0,
                "AGNO": 2020.0,
                "RBD": 1148.0,
                "DGV_RBD": 7.0,
                "NOM_RBD": "LICEO JOSE MANUEL BORGONO NUNEZ",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CUARTEL",
                "NUMERO": 145.0,
                "REFERENCIA": "CUARTEL 145 PETORCA, FRENTE A LA PLAZA DE PETORCA AL ORIENTE.",
                "LATITUD": -32.251511,
                "LONGITUD": -70.930328,
                "MAT_TOT": 421.0,
                "MAT_PARV": 23.0,
                "MAT_BAS_RE": 183.0,
                "MAT_BAS_AD": 3.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 133.0,
                "MAT_MHC_AD": 48.0,
                "MAT_MTP_RE": 31.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 225.0,
                "MAT_MUJ_TO": 196.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 409.0,
                "MAT_EXT": 12.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 7.0,
                "MAT_NO_ETN": 413.0,
                "MAT_SI_ETN": 1.0,
                "CUR_SIM_TO": 24.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.930328,
                    -32.251511
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 810.0,
                "AGNO": 2020.0,
                "RBD": 1149.0,
                "DGV_RBD": 5.0,
                "NOM_RBD": "LICEO CORDILLERA",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "PEDRO MONTT",
                "NUMERO": 0.0,
                "REFERENCIA": "PEDRO MONTT S/N CHINCOLCO   CALLE PRINCIPAL.",
                "LATITUD": -32.22171,
                "LONGITUD": -70.832336,
                "MAT_TOT": 202.0,
                "MAT_PARV": 20.0,
                "MAT_BAS_RE": 96.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 5.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 81.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 113.0,
                "MAT_MUJ_TO": 89.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 197.0,
                "MAT_EXT": 5.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 2.0,
                "MAT_NO_ETN": 200.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 15.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.832336,
                    -32.22171
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 811.0,
                "AGNO": 2020.0,
                "RBD": 1150.0,
                "DGV_RBD": 9.0,
                "NOM_RBD": "ESCUELA BASICA NEFTALI REYES B.",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "PRINCIPAL MANUEL MONTT",
                "NUMERO": 0.0,
                "REFERENCIA": "CORREDORES MANUEL MONTT",
                "LATITUD": -32.321411,
                "LONGITUD": -71.058487,
                "MAT_TOT": 7.0,
                "MAT_PARV": 0.0,
                "MAT_BAS_RE": 2.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 5.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 5.0,
                "MAT_MUJ_TO": 2.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 7.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 7.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 1.0,
                "CUR_COMB_T": 1.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.058487,
                    -32.321411
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 812.0,
                "AGNO": 2020.0,
                "RBD": 1151.0,
                "DGV_RBD": 7.0,
                "NOM_RBD": "ESCUELA BASICA VILLA SANTA ANA",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CALLE LARGA CHINCOLCO",
                "NUMERO": 0.0,
                "REFERENCIA": "CAMINO AL PEDERNAL",
                "LATITUD": -32.179588,
                "LONGITUD": -70.811203,
                "MAT_TOT": 4.0,
                "MAT_PARV": 0.0,
                "MAT_BAS_RE": 4.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 1.0,
                "MAT_MUJ_TO": 3.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 4.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 4.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 0.0,
                "CUR_COMB_T": 1.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.811203,
                    -32.179588
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 813.0,
                "AGNO": 2020.0,
                "RBD": 1152.0,
                "DGV_RBD": 5.0,
                "NOM_RBD": "ESCUELA EDUARDO FREI MONTALVA",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CAMINO PUBLICO",
                "NUMERO": 8.0,
                "REFERENCIA": "CAMINO PUBLICO KM-08 LA POLCURA   COMUNA DE PETORCA V REGI\u00d3N",
                "LATITUD": -32.238201,
                "LONGITUD": -70.874077,
                "MAT_TOT": 71.0,
                "MAT_PARV": 11.0,
                "MAT_BAS_RE": 60.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 43.0,
                "MAT_MUJ_TO": 28.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 70.0,
                "MAT_EXT": 1.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 1.0,
                "MAT_NO_ETN": 70.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 6.0,
                "CUR_COMB_T": 1.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.874077,
                    -32.238201
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 814.0,
                "AGNO": 2020.0,
                "RBD": 1153.0,
                "DGV_RBD": 3.0,
                "NOM_RBD": "ESCUELA BASICA EL CRUCERO",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CALLE PUBLICA EL PEDERNAL",
                "NUMERO": 0.0,
                "REFERENCIA": "AL INTERIOR DE LA COMUNA DE PETORCA (NORESTE), EN LA PRECORDILLERA.",
                "LATITUD": -32.0923,
                "LONGITUD": -70.800072,
                "MAT_TOT": 2.0,
                "MAT_PARV": 0.0,
                "MAT_BAS_RE": 2.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 0.0,
                "MAT_MUJ_TO": 2.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 2.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 2.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 0.0,
                "CUR_COMB_T": 1.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.800072,
                    -32.0923
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 815.0,
                "AGNO": 2020.0,
                "RBD": 1156.0,
                "DGV_RBD": 8.0,
                "NOM_RBD": "ESCUELA BASICA G-24",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CAMINO INTERIOR A ILLAPEL PALQUICO",
                "NUMERO": 0.0,
                "REFERENCIA": "CAMINO INTERIOR A ILLAPEL POR PUENTE PEDEGUA.",
                "LATITUD": -32.252949,
                "LONGITUD": -71.137863,
                "MAT_TOT": 41.0,
                "MAT_PARV": 0.0,
                "MAT_BAS_RE": 41.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 19.0,
                "MAT_MUJ_TO": 22.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 40.0,
                "MAT_EXT": 1.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 1.0,
                "MAT_NO_ETN": 40.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 2.0,
                "CUR_COMB_T": 3.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.137863,
                    -32.252949
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 816.0,
                "AGNO": 2020.0,
                "RBD": 1157.0,
                "DGV_RBD": 6.0,
                "NOM_RBD": "ESCUELA BASICA LOS ALAMOS EL SOBRANTE",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CAMINO PUBLICO EL SOBRANTE",
                "NUMERO": 0.0,
                "REFERENCIA": "CAMINO P\u001aBLICO S/N EL SOBRANTE",
                "LATITUD": -32.227631,
                "LONGITUD": -70.807617,
                "MAT_TOT": 37.0,
                "MAT_PARV": 6.0,
                "MAT_BAS_RE": 31.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 20.0,
                "MAT_MUJ_TO": 17.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 37.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 37.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 1.0,
                "CUR_COMB_T": 4.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.807617,
                    -32.227631
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 817.0,
                "AGNO": 2020.0,
                "RBD": 1158.0,
                "DGV_RBD": 4.0,
                "NOM_RBD": "ESCUELA BASICA BENANCIO PEREZ",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CAMINO INTERIOR A ILLAPEL",
                "NUMERO": 0.0,
                "REFERENCIA": "LAS PALMAS, DE PETORCA.CAMINO PALQUICO.",
                "LATITUD": -32.196499,
                "LONGITUD": -71.132347,
                "MAT_TOT": 5.0,
                "MAT_PARV": 0.0,
                "MAT_BAS_RE": 5.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 1.0,
                "MAT_MUJ_TO": 4.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 5.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 3.0,
                "MAT_NO_ETN": 2.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 0.0,
                "CUR_COMB_T": 1.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.132347,
                    -32.196499
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 818.0,
                "AGNO": 2020.0,
                "RBD": 1160.0,
                "DGV_RBD": 6.0,
                "NOM_RBD": "ESCUELA HOGAR FRONTERIZA DE CHALACO",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CAMINO PUBLICO CHALACO",
                "NUMERO": 0.0,
                "REFERENCIA": "CAMINO PUBLICO CHALACO S/N CHINCOLCO.",
                "LATITUD": -32.187481,
                "LONGITUD": -70.803452,
                "MAT_TOT": 12.0,
                "MAT_PARV": 3.0,
                "MAT_BAS_RE": 9.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 6.0,
                "MAT_MUJ_TO": 6.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 12.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 12.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 0.0,
                "CUR_COMB_T": 2.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.803452,
                    -32.187481
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 819.0,
                "AGNO": 2020.0,
                "RBD": 1161.0,
                "DGV_RBD": 4.0,
                "NOM_RBD": "ESCUELA BASICA PEDEGUA",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CALLE PRINCIPAL",
                "NUMERO": 261.0,
                "REFERENCIA": "PASADO EL T\u00daNEL DE CABILDO CAMINO HACIA LA CORDILLERA",
                "LATITUD": -32.357109,
                "LONGITUD": -71.069817,
                "MAT_TOT": 169.0,
                "MAT_PARV": 28.0,
                "MAT_BAS_RE": 141.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 96.0,
                "MAT_MUJ_TO": 73.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 168.0,
                "MAT_EXT": 1.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 9.0,
                "MAT_NO_ETN": 157.0,
                "MAT_SI_ETN": 3.0,
                "CUR_SIM_TO": 10.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.069817,
                    -32.357109
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 820.0,
                "AGNO": 2020.0,
                "RBD": 1162.0,
                "DGV_RBD": 2.0,
                "NOM_RBD": "ESCUELA PARTICULAR JUAN PABLO II",
                "TIPO_DEPEN": "PARTICULAR SUBVENCIONADO",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "PARAISO PERDIDO",
                "NUMERO": 0.0,
                "REFERENCIA": "ROTONDA MANUEL MONTT, DOBLAR A LA IZQUIERDA HACIA SANTA JULIA.",
                "LATITUD": -32.31422,
                "LONGITUD": -71.069588,
                "MAT_TOT": 41.0,
                "MAT_PARV": 9.0,
                "MAT_BAS_RE": 32.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 23.0,
                "MAT_MUJ_TO": 18.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 41.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 40.0,
                "MAT_SI_ETN": 1.0,
                "CUR_SIM_TO": 1.0,
                "CUR_COMB_T": 3.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.069588,
                    -32.31422
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 821.0,
                "AGNO": 2020.0,
                "RBD": 1164.0,
                "DGV_RBD": 9.0,
                "NOM_RBD": "COL. CATOLICO PDTE.MANUEL MONTT",
                "TIPO_DEPEN": "PARTICULAR SUBVENCIONADO",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "SILVA",
                "NUMERO": 615.0,
                "REFERENCIA": "COLEGIO DE COLOR CELESTE, UBICADO FRENTE A PLAZA DE ARMAS.",
                "LATITUD": -32.25119,
                "LONGITUD": -70.931534,
                "MAT_TOT": 502.0,
                "MAT_PARV": 55.0,
                "MAT_BAS_RE": 295.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 152.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 240.0,
                "MAT_MUJ_TO": 262.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 498.0,
                "MAT_EXT": 4.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 3.0,
                "MAT_NO_ETN": 499.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 14.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.931534,
                    -32.25119
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 822.0,
                "AGNO": 2020.0,
                "RBD": 1166.0,
                "DGV_RBD": 5.0,
                "NOM_RBD": "COLEGIO SAGRADO CORAZON",
                "TIPO_DEPEN": "PARTICULAR SUBVENCIONADO",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "PEDRO MONTT",
                "NUMERO": 0.0,
                "REFERENCIA": "PEDRO MONTT S/N CHINCOLCO",
                "LATITUD": -32.22414,
                "LONGITUD": -70.843201,
                "MAT_TOT": 136.0,
                "MAT_PARV": 25.0,
                "MAT_BAS_RE": 111.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 61.0,
                "MAT_MUJ_TO": 75.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 135.0,
                "MAT_EXT": 1.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 3.0,
                "MAT_NO_ETN": 132.0,
                "MAT_SI_ETN": 1.0,
                "CUR_SIM_TO": 10.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.843201,
                    -32.22414
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 7559.0,
                "AGNO": 2020.0,
                "RBD": 14329.0,
                "DGV_RBD": 4.0,
                "NOM_RBD": "ANEXO LICEO JOSE MANUEL BORGONO NUNEZ",
                "TIPO_DEPEN": "MUNICIPAL",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "SILVA",
                "NUMERO": 60.0,
                "REFERENCIA": "INTERIOR UNIDAD PENAL PETORCA",
                "LATITUD": -32.251372,
                "LONGITUD": -70.930267,
                "MAT_TOT": 9.0,
                "MAT_PARV": 0.0,
                "MAT_BAS_RE": 0.0,
                "MAT_BAS_AD": 9.0,
                "MAT_ESP": 0.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 9.0,
                "MAT_MUJ_TO": 0.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 9.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 0.0,
                "MAT_NO_ETN": 9.0,
                "MAT_SI_ETN": 0.0,
                "CUR_SIM_TO": 3.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.930267,
                    -32.251372
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 11795.0,
                "AGNO": 2020.0,
                "RBD": 40364.0,
                "DGV_RBD": 4.0,
                "NOM_RBD": "ESC.ESP.DE LENGUAJE CUMBRES DE PETORCA",
                "TIPO_DEPEN": "PARTICULAR SUBVENCIONADO",
                "TIPO_SOSTE": "PERSONA JUR\u00cdDICA",
                "COD_REG": 5.0,
                "COD_PROV": 54.0,
                "NOM_PROV": "PETORCA",
                "COD_DEPROV": 51.0,
                "NOM_DEPROV": "QUILLOTA",
                "COD_COM": 5404.0,
                "NOM_COM": "PETORCA",
                "DIRECCION": "CALLE SILVA",
                "NUMERO": 555.0,
                "REFERENCIA": "CENTRO DE LA COMUNA",
                "LATITUD": -32.260513,
                "LONGITUD": -70.9295,
                "MAT_TOT": 39.0,
                "MAT_PARV": 0.0,
                "MAT_BAS_RE": 0.0,
                "MAT_BAS_AD": 0.0,
                "MAT_ESP": 39.0,
                "MAT_MHC_RE": 0.0,
                "MAT_MHC_AD": 0.0,
                "MAT_MTP_RE": 0.0,
                "MAT_MTP_AD": 0.0,
                "MAT_HOM_TO": 24.0,
                "MAT_MUJ_TO": 15.0,
                "MAT_SI_TO": 0.0,
                "MAT_CHI": 39.0,
                "MAT_EXT": 0.0,
                "MAT_NAC": 0.0,
                "MAT_ETNIA": 2.0,
                "MAT_NO_ETN": 26.0,
                "MAT_SI_ETN": 11.0,
                "CUR_SIM_TO": 1.0,
                "CUR_COMB_T": 0.0
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.9295,
                    -32.260513
                ]
            }
        }
    ]
};