var Estab_Educ_parvularia_Petorca_ = {
    "type": "FeatureCollection",
    "name": "Estab_Educ_parvularia_Petorca repro",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        }
    },
    "features": [
        {
            "type": "Feature",
            "properties": {
                "fid": 158.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 50201.0,
                "ORIGEN": 3.0,
                "NOM_ESTAB": "JORGE SABAL RABI",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 5.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "PASAJE OHIGGINS",
                "NUMERO": 0.0,
                "REFERENCIA": "S/N",
                "LATITUD": -32.231554,
                "LONGITUD": -70.854669,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 5.0,
                "MED_MEN_M": 4.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 10.0,
                "MED_MAY_M": 6.0,
                "NT1_H": 2.0,
                "NT1_M": 1.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 28.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.854669,
                    -32.231554
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 159.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 50202.0,
                "ORIGEN": 3.0,
                "NOM_ESTAB": "RAYITO DE LUNA",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 5.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "BERNARDO OHIGGINS",
                "NUMERO": 0.0,
                "REFERENCIA": "S/N",
                "LATITUD": -32.284127,
                "LONGITUD": -70.972561,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 1.0,
                "SC_MAY_M": 1.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 9.0,
                "MED_MEN_M": 2.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 1.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 1.0,
                "NT1_M": 0.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 15.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.972561,
                    -32.284127
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 160.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 50203.0,
                "ORIGEN": 3.0,
                "NOM_ESTAB": "TRENCITO",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 5.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "CALLE PRINCIPAL",
                "NUMERO": 0.0,
                "REFERENCIA": "S/N",
                "LATITUD": -32.358414,
                "LONGITUD": -71.067839,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 1.0,
                "MED_MEN_M": 3.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 4.0,
                "MED_MAY_M": 5.0,
                "NT1_H": 2.0,
                "NT1_M": 2.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 17.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.067839,
                    -32.358414
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 1782.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 5404001.0,
                "ORIGEN": 2.0,
                "NOM_ESTAB": "LAMPARITA",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 4.0,
                "RURAL_ESTA": 0.0,
                "ESTADO_EST": null,
                "DIRECCION": "CALLE EL LITRE",
                "NUMERO": 0.0,
                "REFERENCIA": "S/N POBLACION LACION GRUTA 2",
                "LATITUD": -32.248774,
                "LONGITUD": -70.924841,
                "SC_MEN_H": 10.0,
                "SC_MEN_M": 5.0,
                "SC_MAY_H": 9.0,
                "SC_MAY_M": 11.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 11.0,
                "MED_MAY_M": 11.0,
                "NT1_H": 14.0,
                "NT1_M": 7.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 78.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.9248407699999,
                    -32.2487743999999
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 1783.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 5404002.0,
                "ORIGEN": 2.0,
                "NOM_ESTAB": "MUNDO DE PEQUES-CHINCOLCO",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 4.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "CALLE PUBLICA",
                "NUMERO": 1.0,
                "REFERENCIA": "POBLACION OHIGGINS CHINCOLCO",
                "LATITUD": -32.221535,
                "LONGITUD": -70.832312,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 1.0,
                "SC_MAY_H": 11.0,
                "SC_MAY_M": 3.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 0.0,
                "NT1_M": 0.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 15.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.8323116989999,
                    -32.22153474
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 1784.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 5404003.0,
                "ORIGEN": 2.0,
                "NOM_ESTAB": "MIS PRIMEROS PASOS",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 4.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "CALLE SAN RAMON",
                "NUMERO": 8.0,
                "REFERENCIA": "CALLE SAN RAMON N8PEDEGUA",
                "LATITUD": -32.357607,
                "LONGITUD": -71.070238,
                "SC_MEN_H": 1.0,
                "SC_MEN_M": 1.0,
                "SC_MAY_H": 2.0,
                "SC_MAY_M": 7.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 0.0,
                "NT1_M": 0.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 11.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.07023799,
                    -32.357607377
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 1785.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 5404104.0,
                "ORIGEN": 2.0,
                "NOM_ESTAB": "PMI-RISITOS DE ORO",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 4.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "CAMINO FISCAL AL NORTE",
                "NUMERO": 18.0,
                "REFERENCIA": "CAMINO FISCAL AL NORTE KM 18 PALQUICO",
                "LATITUD": -32.252741,
                "LONGITUD": -71.138709,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 1.0,
                "MED_MEN_M": 5.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 1.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 4.0,
                "NT1_M": 1.0,
                "NT2_H": 1.0,
                "NT2_M": 0.0,
                "N_TOTAL": 13.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.13870868,
                    -32.25274050099989
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 1786.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 5404105.0,
                "ORIGEN": 2.0,
                "NOM_ESTAB": "PMI-ARBOLITO",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 4.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "CALLE PEDRO MONTT",
                "NUMERO": 0.0,
                "REFERENCIA": "S/NCHINCOLCO",
                "LATITUD": -32.230738,
                "LONGITUD": -70.851617,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 2.0,
                "MED_MEN_M": 2.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 5.0,
                "MED_MAY_M": 1.0,
                "NT1_H": 1.0,
                "NT1_M": 0.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 11.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.851617,
                    -32.230738
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 1787.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 5404106.0,
                "ORIGEN": 2.0,
                "NOM_ESTAB": "PMI-LAS PALMITAS",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 4.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "CAMINO INTERIOR A ILLAPEL",
                "NUMERO": 23.0,
                "REFERENCIA": "CAMINO INTERIOR A ILLAPEL KILOMETRO 23",
                "LATITUD": -32.196331,
                "LONGITUD": -71.132254,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 1.0,
                "MED_MEN_M": 2.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 4.0,
                "MED_MAY_M": 1.0,
                "NT1_H": 0.0,
                "NT1_M": 0.0,
                "NT2_H": 0.0,
                "NT2_M": 2.0,
                "N_TOTAL": 10.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.132254,
                    -32.196331
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 1788.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 5404106.999999999,
                "ORIGEN": 2.0,
                "NOM_ESTAB": "TRENCITO",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": null,
                "NOM_DEPROV": null,
                "DEPENDENCI": 4.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": null,
                "DIRECCION": "SANTA JULIA",
                "NUMERO": 0.0,
                "REFERENCIA": "S/N",
                "LATITUD": -32.309414,
                "LONGITUD": -71.072358,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 4.0,
                "MED_MEN_M": 3.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 4.0,
                "MED_MAY_M": 1.0,
                "NT1_H": 1.0,
                "NT1_M": 0.0,
                "NT2_H": 0.0,
                "NT2_M": 0.0,
                "N_TOTAL": 13.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.072358,
                    -32.309414
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5201.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1147.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "ESCUELA FERNANDO GARCIA OLDINI",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 1.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "COMERCIO HIERRO VIEJO",
                "NUMERO": 36.0,
                "REFERENCIA": "CALLE PRINCIPAL",
                "LATITUD": -32.28054,
                "LONGITUD": -71.011673,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 7.0,
                "NT1_M": 8.0,
                "NT2_H": 4.0,
                "NT2_M": 7.0,
                "N_TOTAL": 26.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.011673,
                    -32.28054
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5202.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1148.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "LICEO JOSE MANUEL BORGONO NUNEZ",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 1.0,
                "RURAL_ESTA": 0.0,
                "ESTADO_EST": "1",
                "DIRECCION": "CUARTEL",
                "NUMERO": 145.0,
                "REFERENCIA": "CUARTEL 145 PETORCA, FRENTE A LA PLAZA DE PETORCA AL ORIENTE.",
                "LATITUD": -32.251511,
                "LONGITUD": -70.930328,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 4.0,
                "NT1_M": 4.0,
                "NT2_H": 9.0,
                "NT2_M": 6.0,
                "N_TOTAL": 23.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.930328,
                    -32.251511
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5203.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1149.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "LICEO CORDILLERA",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 1.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "PEDRO MONTT",
                "NUMERO": 0.0,
                "REFERENCIA": "PEDRO MONTT S/N CHINCOLCO   CALLE PRINCIPAL.",
                "LATITUD": -32.22171,
                "LONGITUD": -70.832336,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 6.0,
                "NT1_M": 5.0,
                "NT2_H": 6.0,
                "NT2_M": 3.0,
                "N_TOTAL": 20.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.832336,
                    -32.22171
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5204.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1152.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "ESCUELA EDUARDO FREI MONTALVA",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 1.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "CAMINO PUBLICO",
                "NUMERO": 8.0,
                "REFERENCIA": "CAMINO PUBLICO KM-08 LA POLCURA   COMUNA DE PETORCA V REGI\u00d3N",
                "LATITUD": -32.238201,
                "LONGITUD": -70.874077,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 3.0,
                "NT1_M": 3.0,
                "NT2_H": 2.0,
                "NT2_M": 3.0,
                "N_TOTAL": 11.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.874077,
                    -32.238201
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5205.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1157.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "ESCUELA BASICA LOS ALAMOS EL SOBRANTE",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 1.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "CAMINO PUBLICO EL SOBRANTE",
                "NUMERO": 0.0,
                "REFERENCIA": "CAMINO P\u001aBLICO S/N EL SOBRANTE",
                "LATITUD": -32.227631,
                "LONGITUD": -70.807617,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 1.0,
                "NT1_M": 3.0,
                "NT2_H": 1.0,
                "NT2_M": 1.0,
                "N_TOTAL": 6.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.807617,
                    -32.227631
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5206.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1160.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "ESCUELA HOGAR FRONTERIZA DE CHALACO",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 1.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "CAMINO PUBLICO CHALACO",
                "NUMERO": 0.0,
                "REFERENCIA": "CAMINO PUBLICO CHALACO S/N CHINCOLCO.",
                "LATITUD": -32.187481,
                "LONGITUD": -70.803452,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 0.0,
                "NT1_M": 0.0,
                "NT2_H": 1.0,
                "NT2_M": 2.0,
                "N_TOTAL": 3.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.803452,
                    -32.187481
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5207.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1161.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "ESCUELA BASICA PEDEGUA",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 1.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "CALLE PRINCIPAL",
                "NUMERO": 261.0,
                "REFERENCIA": "PASADO EL T\u00daNEL DE CABILDO CAMINO HACIA LA CORDILLERA",
                "LATITUD": -32.357109,
                "LONGITUD": -71.069817,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 7.0,
                "NT1_M": 4.0,
                "NT2_H": 10.0,
                "NT2_M": 7.0,
                "N_TOTAL": 28.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.069817,
                    -32.357109
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5208.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1162.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "ESCUELA PARTICULAR JUAN PABLO II",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 2.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "PARAISO PERDIDO",
                "NUMERO": 0.0,
                "REFERENCIA": "ROTONDA MANUEL MONTT, DOBLAR A LA IZQUIERDA HACIA SANTA JULIA.",
                "LATITUD": -32.31422,
                "LONGITUD": -71.069588,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 4.0,
                "NT1_M": 3.0,
                "NT2_H": 1.0,
                "NT2_M": 1.0,
                "N_TOTAL": 9.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.069588,
                    -32.31422
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5209.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1164.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "COL. CATOLICO PDTE.MANUEL MONTT",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 2.0,
                "RURAL_ESTA": 0.0,
                "ESTADO_EST": "1",
                "DIRECCION": "SILVA",
                "NUMERO": 615.0,
                "REFERENCIA": "COLEGIO DE COLOR CELESTE, UBICADO FRENTE A PLAZA DE ARMAS.",
                "LATITUD": -32.25119,
                "LONGITUD": -70.931534,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 11.0,
                "NT1_M": 17.0,
                "NT2_H": 12.0,
                "NT2_M": 15.0,
                "N_TOTAL": 55.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.931534,
                    -32.25119
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5210.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 1166.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "COLEGIO SAGRADO CORAZON",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 2.0,
                "RURAL_ESTA": 1.0,
                "ESTADO_EST": "1",
                "DIRECCION": "PEDRO MONTT",
                "NUMERO": 0.0,
                "REFERENCIA": "PEDRO MONTT S/N CHINCOLCO",
                "LATITUD": -32.22414,
                "LONGITUD": -70.843201,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 0.0,
                "MED_MAY_M": 0.0,
                "NT1_H": 6.0,
                "NT1_M": 8.0,
                "NT2_H": 5.0,
                "NT2_M": 6.0,
                "N_TOTAL": 25.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.843201,
                    -32.22414
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "fid": 5390.0,
                "AGNO": 2020.0,
                "ID_ESTAB": 40364.0,
                "ORIGEN": 1.0,
                "NOM_ESTAB": "ESC.ESP.DE LENGUAJE CUMBRES DE PETORCA",
                "COD_REG_ES": 5.0,
                "COD_PRO_ES": 54.0,
                "COD_COM_ES": 5404.0,
                "NOM_COM_ES": "PETORCA",
                "COD_DEPROV": "51",
                "NOM_DEPROV": "QUILLOTA",
                "DEPENDENCI": 2.0,
                "RURAL_ESTA": 0.0,
                "ESTADO_EST": "1",
                "DIRECCION": "CALLE SILVA",
                "NUMERO": 555.0,
                "REFERENCIA": "CENTRO DE LA COMUNA",
                "LATITUD": -32.260513,
                "LONGITUD": -70.9295,
                "SC_MEN_H": 0.0,
                "SC_MEN_M": 0.0,
                "SC_MAY_H": 0.0,
                "SC_MAY_M": 0.0,
                "MED_MEN_SI": 0.0,
                "MED_MEN_H": 0.0,
                "MED_MEN_M": 0.0,
                "MED_MAY_SI": 0.0,
                "MED_MAY_H": 10.0,
                "MED_MAY_M": 5.0,
                "NT1_H": 7.0,
                "NT1_M": 6.0,
                "NT2_H": 7.0,
                "NT2_M": 4.0,
                "N_TOTAL": 39.0,
                "Cuenta Pub": null
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -70.9295,
                    -32.260513
                ]
            }
        }
    ]
};